import{d as I,u as j,q as B,o,c as l,b as t,f as D,F as f,r as b,h as k,t as h,j as m,v as S,x as V,z,i as T,B as g,D as $}from"./index.js";import{_ as N}from"./ModelSelector.vue_vue_type_script_setup_true_lang.js";const E={class:"max-w-4xl mx-auto h-[calc(100vh-8rem)] flex flex-col"},F={class:"flex items-center justify-between mb-4"},H={class:"whitespace-pre-wrap font-sans text-sm leading-relaxed"},K={key:0,class:"flex justify-start"},L={key:0,class:"mt-4"},P={class:"flex flex-wrap gap-2"},Q=["onClick"],U={class:"mt-4 flex gap-3"},q={class:"flex-1 relative"},G=["disabled"],J=["disabled"],X=I({__name:"AIAssistantView",setup(O){const y=j(),a=g([]),r=g(""),i=g(!1),u=g(null),p=async()=>{if(!r.value.trim()||i.value)return;if(!y.isConfigured){d("assistant","请先在设置页面配置 AI API，才能使用 AI 助手功能。");return}const n=r.value.trim();r.value="",d("user",n),i.value=!0;try{const e=y.getService(),s=a.value.slice(-10).map(c=>({role:c.role,content:c.content}));let v="";const A=d("assistant",""),M=`你是一位专业的电商运营顾问，精通各大电商平台的运营策略。
你的任务是帮助商家解决电商运营中遇到的各种问题，包括：
- 店铺运营策略
- 产品选品建议
- 营销活动策划
- 数据分析解读
- 客户运营技巧
- 直播带货指导

请用专业、友善、实用的方式回答用户的问题。如果问题不明确，可以适当追问。`;for await(const c of e.chatStream([...s,{role:"user",content:n}],M))v+=c,A.content=v,x()}catch(e){d("assistant",`抱歉，出现了错误：${e instanceof Error?e.message:"请稍后重试"}`)}finally{i.value=!1,x()}},d=(n,e)=>{const s={id:`msg-${Date.now()}`,role:n,content:e,timestamp:Date.now()};return a.value.push(s),s},x=()=>{$(()=>{u.value&&(u.value.scrollTop=u.value.scrollHeight)})},_=()=>{a.value=[]},w=["如何提高店铺转化率？","新手开淘宝店需要做什么准备？","如何写出吸引人的商品标题？","抖音直播带货有什么技巧？","如何做竞品分析？"],C=n=>{r.value=n,p()};return B(()=>{a.value.length===0&&d("assistant",`你好！我是电商军师 AI 助手 🤖

我可以帮你解答电商运营相关的问题，比如店铺运营、选品策略、营销活动、数据分析等。

请问有什么可以帮助你的？`)}),(n,e)=>(o(),l("div",E,[t("div",F,[e[1]||(e[1]=t("h2",{class:"text-xl font-bold text-gray-800 dark:text-gray-200"}," AI 助手 ",-1)),D(N,{"model-type":"text","show-label":!0,size:"md"})]),t("div",{ref_key:"messagesContainer",ref:u,class:"flex-1 overflow-y-auto space-y-4 p-4 bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700"},[(o(!0),l(f,null,b(a.value,s=>(o(),l("div",{key:s.id,class:k(["flex",s.role==="user"?"justify-end":"justify-start"])},[t("div",{class:k(["max-w-[80%] rounded-2xl px-4 py-3",s.role==="user"?"bg-primary-600 text-white rounded-br-sm":"bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-bl-sm"])},[t("pre",H,h(s.content),1)],2)],2))),128)),i.value?(o(),l("div",K,[...e[2]||(e[2]=[t("div",{class:"bg-gray-100 dark:bg-gray-700 rounded-2xl px-4 py-3 rounded-bl-sm"},[t("span",{class:"animate-pulse text-gray-700 dark:text-gray-300"},"正在思考中...")],-1)])])):m("",!0)],512),a.value.length<=2?(o(),l("div",L,[e[3]||(e[3]=t("p",{class:"text-sm text-gray-500 dark:text-gray-400 mb-2"}," 你可以问我： ",-1)),t("div",P,[(o(),l(f,null,b(w,s=>t("button",{key:s,class:"px-3 py-1.5 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-full text-sm text-gray-700 dark:text-gray-300 transition-colors",onClick:v=>C(s)},h(s),9,Q)),64))])])):m("",!0),t("div",U,[a.value.length>1?(o(),l("button",{key:0,class:"btn-secondary",title:"清空对话",onClick:_}," 🗑️ ")):m("",!0),t("div",q,[S(t("input",{"onUpdate:modelValue":e[0]||(e[0]=s=>r.value=s),type:"text",placeholder:"输入你的问题...",class:"input pr-12",disabled:i.value,onKeyup:z(p,["enter"])},null,40,G),[[V,r.value]]),t("button",{disabled:!r.value.trim()||i.value||!T(y).isConfigured,class:"absolute right-2 top-1/2 -translate-y-1/2 p-2 rounded-lg bg-primary-600 text-white disabled:opacity-50 disabled:cursor-not-allowed",onClick:p},[...e[4]||(e[4]=[t("svg",{class:"w-5 h-5",fill:"none",stroke:"currentColor",viewBox:"0 0 24 24"},[t("path",{"stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"2",d:"M12 19l9 2-9-18-9 18 9-2zm0 0v-8"})],-1)])],8,J)])])]))}});export{X as default};
